package innbucks.paymentservice.entity;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.Id;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.util.UUID;

/**
 * One row per money-movement attempt — see {@code V1__transactions.sql}
 * for column-level intent and {@link TransactionStatus} for the lifecycle.
 *
 * <p>The {@code id} is assigned client-side (we do {@code UUID.randomUUID()}
 * before the first INSERT) rather than generated by the DB. That lets the
 * controller log the txId before the row commits and makes
 * {@link TransactionStatus#PENDING}-→-{@code SUCCEEDED} updates a simple
 * lookup by primary key.
 */
@Entity
@Table(name = "transactions")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Transaction {

    @Id
    private UUID id;

    @Enumerated(EnumType.STRING)
    @Column(name = "transaction_type", nullable = false, length = 32)
    private TransactionType transactionType;

    @Column(name = "customer_phone", nullable = false, length = 32)
    private String customerPhone;

    @Column(name = "source_account_id", nullable = false, length = 64)
    private String sourceAccountId;

    @Column(name = "destination_account_id", length = 64)
    private String destinationAccountId;

    @Column(nullable = false, precision = 19, scale = 4)
    private BigDecimal amount;

    @Column(length = 8)
    private String currency;

    @Column(name = "payment_method_name", length = 64)
    private String paymentMethodName;

    @Column(length = 500)
    private String notes;

    @Column(name = "transaction_date", nullable = false)
    private LocalDate transactionDate;

    @Column(name = "transaction_branch_id", length = 64)
    private String transactionBranchId;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 16)
    private TransactionStatus status;

    @Column(name = "idempotency_key", length = 128)
    private String idempotencyKey;

    @Column(name = "oradian_transaction_id", length = 64)
    private String oradianTransactionId;

    @Column(name = "oradian_reference_number", length = 64)
    private String oradianReferenceNumber;

    @Column(name = "oradian_command_id", length = 64)
    private String oradianCommandId;

    @Column(name = "failure_code", length = 64)
    private String failureCode;

    @Column(name = "failure_message", length = 500)
    private String failureMessage;

    @Column(name = "correlation_id", length = 64)
    private String correlationId;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    @Column(name = "completed_at")
    private Instant completedAt;

    @PrePersist
    void prePersist() {
        if (id == null) id = UUID.randomUUID();
        if (createdAt == null) createdAt = Instant.now();
        if (status == null) status = TransactionStatus.PENDING;
    }
}
