package com.innbucks.userservice.dto;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;

@Data
@Schema(name = "DeviceRegistration",
        description = "Device details captured at Tier-3 registration for trusted-device tracking.")
public class DeviceRegistrationDTO {

    @Schema(example = "f8a2c4e6-1234-5678-abcd-ef0123456789",
            description = "Unique device identifier generated by the client SDK.")
    @NotBlank(message = "Device ID is required")
    private String deviceId;

    @Schema(example = "Alice's iPhone 15 Pro", nullable = true)
    private String deviceName;

    @Schema(example = "iOS", nullable = true,
            allowableValues = {"iOS", "Android", "Web"},
            description = "Operating system / platform of the device.")
    private String platform;

    @Schema(example = "ExponentPushToken[xxxxxxxxxxxxxxxxxxxxxx]", nullable = true,
            description = "Push notification token for this device. Used to send OTP and alerts.")
    private String pushToken;
}
