package com.innbucks.eventservice.entity;

import jakarta.persistence.*;
import lombok.*;
import org.hibernate.annotations.Generated;
import org.hibernate.generator.EventType;

import java.time.LocalDateTime;
import java.util.UUID;

@Entity
@Table(name = "events")
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class Event {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID eventId;

    // Sequential public-facing event number, starts at 1 and auto-increments.
    // The database owns the counter via an IDENTITY column so concurrent
    // inserts can't collide or skip. Hibernate reads the assigned value back
    // after INSERT (@Generated(event = INSERT) + insertable=false).
    @Column(
            name = "event_no",
            nullable = false,
            unique = true,
            insertable = false,
            updatable = false,
            columnDefinition = "INTEGER GENERATED BY DEFAULT AS IDENTITY"
    )
    @Generated(event = EventType.INSERT)
    private Integer eventNo;

    @Column(nullable = false)
    private String agentId;

    @Column(nullable = false)
    private String title;

    @Column(columnDefinition = "TEXT")
    private String description;

    @Column(nullable = false)
    private String venue;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 3)
    private Province province;

    @Column(nullable = false)
    private LocalDateTime dateTime;

    @Column(nullable = false)
    private Integer totalCapacity;

    @Column(nullable = false)
    private Integer availableTickets;

    @Column(nullable = false)
    private boolean deleted = false;

    @Column(updatable = false)
    private LocalDateTime createdAt;

    private LocalDateTime updatedAt;

    @PrePersist
    public void onCreate() {
        this.createdAt = LocalDateTime.now();
    }

    @PreUpdate
    public void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }
}
